travis:
  secure:
    BINSTAR_TOKEN: dkp9SmiINTLvzCdWbbh3lUyPd3mBQoqPEa/grfQrXQEjuKp6yGe0OyblrJcjAV37srfobHCGqACx8H13brwv33oqp2yxlaeKZDOBDwZpbWdU2iuLGknSOe20m/QXFtx6gJtBUKhxOiJ2zuurnsOZfAqXv5+eOSxKgf05o/472F2cUBsiWsSVRl3bqhTueqxKe60ij/ZFrJ5yddQOERUJc4YMUZOMrbTs7z6u0BZmULVHFs0FCeczqlF/2M0ZDlOpQgqDvUF5OzdM8pNcHFxDk6MkGFDBzv8oiU++qbNQTM8gd2KeraqtnelPQEfrzGhmkKe1Qr5D92u3MjOG4k/GNUFhJ61XhzUueb1TDOBGDQqF6XziiEWKSMcg7jyF4D5txXgmwsfCv3q5vpsjloKnu7vr6ty3WVsOpVpp+hIx4RTXzvbIqppQ+Kl9FIuxYlVUiSoKc4L+Bvb7vDL60k9YAS56zYQEgFU60mDdy0u6NZ56sCiWWPBv6fJXcHQnE54t2UCa7jzCUzqwZAanron1J1iGkQzX5z6UkdGHTeJ2VSwXtXkWyPO/gGyBKFH6dE/c9dXs/fZU6YcCCdPzJYVX0rul7f2n9BC6SlPLA2RUYpb6om1/4RL2uhmD6DSS4FR4hq8DQqk4KYHw3hoWAFpjMmIRc4jXtACP+N/2iG7Bkck=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
